cache:
  paths:
    - node_modules

stages:
  - build
  - run

variables:
  S3_BUCKET_DEV: ${BUCKET_DEV}
  S3_BUCKET_PROD: ${BUCKET_PROD}

.yarn_build:
  image: node:14
  script: |
    yarn
    yarn build
  artifacts:
    paths:
      - ./build

yarn_dev:
  extends: .yarn_build
  stage: build
  before_script:
    - export APP_ENV="dev"
    - export REACT_APP_API_URL=${REACT_APP_API_URL_DEV}
  only:
    refs:
      - dev

yarn_prod:
  extends: .yarn_build
  stage: build
  before_script:
    - export APP_ENV="prod"
    - export REACT_APP_API_URL=${REACT_APP_API_URL_PROD}
  only:
    refs:
      - main

.deploy_aws:
  image: python:latest
  script: |
    pip install awscli
    aws s3 rm s3://${S3_BUCKET} --recursive
    aws s3 sync ./build/ s3://${S3_BUCKET}
    aws cloudfront create-invalidation --distribution-id ${CDN_DISTRIBUTION} --paths "/*"

deploy_dev:
  extends: .deploy_aws
  stage: run
  dependencies:
    - yarn_dev
  before_script:
    - export S3_BUCKET=${S3_BUCKET_DEV}
    - echo "env:"
    - env
    - export CDN_DISTRIBUTION=${CDN_DISTRIBUTION_DEV}
  only:
    refs:
      - dev

deploy_prod:
  extends: .deploy_aws
  stage: run
  dependencies:
    - yarn_prod
  before_script:
    - export S3_BUCKET=${S3_BUCKET_PROD}
    - export CDN_DISTRIBUTION=${CDN_DISTRIBUTION_PROD}
  only:
    refs:
      - main
